{% set version = "1.7" %}
{% set sha256 = "1886d6fa1e72cd23be94ac68917cbe11807f4918ceb1a687d460ae1b5f813d57" %}

package:
  name: orca
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/orca/orca-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - orca-server = orca.server.server:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - flask >=0.10
    - pandas >=0.15.0
    - pygments >=2.0
    - pytables >=3.1.0
    - six >=1.9.0
    - toolz >=0.8.1

test:
  imports:
    - orca
    - orca.server
    - orca.utils

  commands:
    - orca-server --help

about:
  home: http://github.com/udst/orca
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python library for task orchestration
  description: |
    Orca is a Python library for task orchestration. It's designed for
    workflows like city simulation, where the data representing a model's
    state is so large that it needs to be managed outside of the task graph.
  doc_url: https://udst.github.io/orca/
  dev_url: http://github.com/udst/orca

extra:
  recipe-maintainers:
    - smmaurer
    - sablanchard
