{% set name = "orca" %}
{% set version = "1.5.2" %}
{% set sha256 = "f4503dc41c555d883ce6b49288465c895244e7cebf9b709889b156e7ef9745ed" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/UDST/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - orca-server = orca.server.server:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - pandas >=0.15.0
    - pytables >=3.1.0
    - toolz >=0.8.1
    - pygments >=2.0
    - flask >=0.10
    - six >=1.9.0

test:
  imports:
    - orca
    - orca.server
    - orca.utils

  commands:
    - orca-server --help

about:
  home: http://github.com/udst/orca
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A pipeline orchestration tool with Pandas support'
  description: |
    Orca is a pipeline orchestration tool that allows you to define dynamic
    data sources and explicitly connect them to processing functions. Orca has
    many features for working with Pandas data structures, but it can be used
    with anything.
  doc_url: https://udst.github.io/orca/
  dev_url: http://github.com/udst/orca

extra:
  recipe-maintainers:
    - pksohn
