travis:
  secure:
    BINSTAR_TOKEN: FeqSzGVCHIT/ecNAMrro0rTznZtx0C7Hch8SfCDgIPJ06wARe6+4c+oxx80p+LVO+6TUXtPgrzcoM1ug8GyBXTedsgE5aAKOrOIohPNaj4hqY/JvpqwrnU5Ui7bdPrRdHBoHk7o0uiuqSwDGgVteTQtctFNsB8ULPe4QXhnoq89L5IpWLboQr1OCDDAuALNh2yuHycijdhSQcRl5gSUbNH/VTgxd7ShX8pUjy+yAhlGvGHcCFbao8R+Cw/a5kkMwAjLoqB4yqQ+JJx1lJmYB5FeXAJYb3JRgX2oF7Qx8CFqdlbEl8hh9BSs39OVp17uSkGp0Eh1OGgMFBYKFXlTIWWTINgfUVAGkM5WEZN3p8/hPLN7GW6B5rSoO0XmjAJVsuYWV9WqiOPEPrBV+ggIuq/oEdAp3B9ZM/X2aeNkdKkEnCDkJF/TRm7taRBhoQ2l3Dp4+Vh2eHWbjsBl6IVSw1aTZ0e+bFtr2pH+UbgrA9JqtGH46ltNAGe9p4ohmGRDN9IDVRtxynGP002EtSJX2579Aw7ue9dSrhDQlA0/CfyvGDcEBRFrF1f9wZB9tJawr4lz+N+MXTo9Fxi+zrMmgDxLvzacCaVGaS/NISb3OXmmOaX/Zw/mQUKYnQWtYK3Q1t4iQXyyYBlTZRXDip2+KPlW5B30MtzjNE4ONkdGvbsc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
