travis:
  secure:
    BINSTAR_TOKEN: BbspDnv0B+l9+YVwE8i6Igdh8QQGdnqlb7HZytCrlJH9RL5nFp0+6dLQaCLo0PSPdJqR5zkLy5g7kJjvUyJfIb59465hqfFxApqjMzhMalNH+YdE82SOBzDCvS1QrIuxNtjCi3KHrl1F456h47oW9zb0K169zkocHKo/iWgOaX5v0RU5f4/10MSgT0By+AvTQhSCoeFv4cMyYpEDjCwcOAih6Nb2mfoGh0K9McWfaoYb5rF33wAVVMOnGMjgM3nlrmES44/edxh4CsxeIUk012zOAT7tRfrsEVtHaKBoo/REUjnR1Fvf6BF87VTgAONOG5WmbbHTlLa6ThD9fwkMSjs7bML5f+WdlL+M+r07BJN1YBH9KlbM1FAxVFoftqNclTLgjjBOPLMOl0pCiXww3ZQ4KxYF3nEBNxlczi7C/lfLuVd0aGgPIBCF37ClcDq/EI3EEA4UmXhxDR7R0D39fAH+vtk7b4BJPWhKmXKWD8q7QFnqCEFQ5M08u8F/n48bBAiDnXYvlKPduvseERlsy0oyk6O8NnNJuzFb/rf/jYT9o62u3O/HWBl5Lwt2JK+4L/XmptXKOuBCgVT4ChJ9vhL315P8I6glxWFGp31ef27OnomiMULvznx/H6FRvxQAEUxuyNfqPx/qazzhUNTfUGdfAv1qjr6bn6/KPAdchgs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
